language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null

script:
  - ./gradlew assembleDebug
  - ls -l app/build/outputs/apk/

cache:
  directories:
    - $HOME/.gradle
