language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew assembleDebug
  - ls -l app/build/outputs/apk/

cache:
  directories:
    - $HOME/.gradle
